### ISSUE TITLE
Unable to load a saved model with Spatial-Pyramid-Layer.

### ISSUE THREAD

**Issue by yash0307** [yhenon/keras-spp#10]
I successfully trained a model using Spatial-Pyramid-Pooling, however for evaluation purposes, I'm unable to load the saved model as SPP doesn't exist in original Keras model load function. Could you please suggest any work-around to this ?

**Comment by yhenon** [comment]
Can you share the error message?

**Comment by JinXinDeep** [comment]
model = load_model(args.corner_weights_path, custom_objects={'SpatialPyramidPooling': SpatialPyramidPooling})
 
just add the custom_objects argument.

**Comment by yash0307** [comment]
@JinXinDeep, thanks for the suggestion. 
I found a work-around by initialising a model first and then loading weights from saved model using model.load_weights(model_path) in keras.
