### ISSUE TITLE
Does spp pooling and RoI pooling support back propagation?

### ISSUE THREAD

**Issue by Evan-Gao** [yhenon/keras-spp#4]
I'm new to keras. It seems the spp pooling layer and RoI pooling layer just support forward operation. Can it be used to train a new network via back propagation?

**Comment by yhenon** [comment]
Hi,
Backpropagation is supported with both the theano and tensorflow backend. 

Both libraries perform the backpropagation step automatically (you may want to read up on automatic differentiation / symbolic differentiation). As such it is not necessary to write extra code for the backwards pass.
