### ISSUE TITLE
Error when using with Keras 2

### ISSUE THREAD

**Issue by fusionlove** [yhenon/keras-spp#6]
The following code gives an error with Keras 2:

```
def test(weights_path=None):
    tr = False
    model = Sequential()
    model.add(ZeroPadding2D((1,1),input_shape=(3,None,None), name='layer_0'))
    model.add(Convolution2D(64, (3, 3), activation='relu', trainable=tr))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(64, (3, 3), activation='relu', trainable=tr))
    model.add(MaxPooling2D((2,2), strides=(2,2)))
    
    model.add(SpatialPyramidPooling([1,2,4]))

    model.add(Dense(2, activation='softmax'))
    
    model.compile(loss=mean_squared_error,
              optimizer='adam')
    return model

t = test()
t.summary()
```

The error is:

> TypeError                                 Traceback (most recent call last)
> <ipython-input-37-7764b5c4e808> in <module>()
> ----> 1 t = test()
>       2 t.summary()
> 
> <ipython-input-36-9ee833dd3809> in test(weights_path)
>      10     model.add(SpatialPyramidPooling([1,2,4]))
>      11 
> ---> 12     model.add(Dense(2, activation='softmax'))
>      13 
>      14     model.compile(loss=mean_squared_error,
> 
> /usr/local/lib/python2.7/dist-packages/keras/models.pyc in add(self, layer)
>     461                           output_shapes=[self.outputs[0]._keras_shape])
>     462         else:
> --> 463             output_tensor = layer(self.outputs[0])
>     464             if isinstance(output_tensor, list):
>     465                 raise TypeError('All layers in a Sequential model '
> 
> /usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in __call__(self, inputs, **kwargs)
>     549                                          '`layer.build(batch_input_shape)`')
>     550                 if len(input_shapes) == 1:
> --> 551                     self.build(input_shapes[0])
>     552                 else:
>     553                     self.build(input_shapes)
> 
> /usr/local/lib/python2.7/dist-packages/keras/layers/core.pyc in build(self, input_shape)
>     825                                       name='kernel',
>     826                                       regularizer=self.kernel_regularizer,
> --> 827                                       constraint=self.kernel_constraint)
>     828         if self.use_bias:
>     829             self.bias = self.add_weight((self.units,),
> 
> /usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in add_weight(self, shape, initializer, name, trainable, regularizer, constraint)
>     382         """
>     383         initializer = initializers.get(initializer)
> --> 384         weight = K.variable(initializer(shape), dtype=K.floatx(), name=name)
>     385         if regularizer is not None:
>     386             self.add_loss(regularizer(weight))
> 
> /usr/local/lib/python2.7/dist-packages/keras/initializers.pyc in __call__(self, shape, dtype)
>     198             scale /= max(1., fan_out)
>     199         else:
> --> 200             scale /= max(1., float(fan_in + fan_out) / 2)
>     201         if self.distribution == 'normal':
>     202             stddev = np.sqrt(scale)
> 
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

Can anyone see what the problem might be?

**Comment by yhenon** [comment]
Are you on the latest version of this repo? It works for me with keras 2.0.3 and theano 0.9.0 (I assume you're using theano based on your channel ordering).
Output:
```
Using Theano backend.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
layer_0 (ZeroPadding2D)      (None, 3, None, None)     0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 64, None, None)    1792      
_________________________________________________________________
zero_padding2d_1 (ZeroPaddin (None, 64, None, None)    0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 64, None, None)    36928     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 64, None, None)    0         
_________________________________________________________________
spatial_pyramid_pooling_1 (S (None, 1344)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 2690      
=================================================================
Total params: 41,410
Trainable params: 2,690
Non-trainable params: 38,720
_________________________________________________________________
```

**Comment by fusionlove** [comment]
I thought I was on the latest version, but wasn't due to a conda environment mess-up. Now that I've sorted that, everything works fine. Thanks for your swift response, OK to close this!

**Comment by hmzzzzzz** [comment]
@yhenon @fusionlove Hello, I got the same problem. The keras version I used is 2.2.4. How to solve the problem? Thank you!
scale /= max(1., float(fan_in + fan_out) / 2)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
